class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start2'
        self.MirrorCommand = 'mirror2'
        self.UnzipMirrorCommand = 'unzipmirror2'
        self.TarMirrorCommand = 'tarmirror2'
        self.ZipMirrorCommand = 'zipmirror2'
        self.CancelMirror = 'cancel2'
        self.CancelAllCommand = 'cancelall2'
        self.ListCommand = 'list2'
        self.StatusCommand = 'status2'
        self.AuthorizedUsersCommand = 'users2'
        self.AuthorizeCommand = 'authorize2'
        self.UnAuthorizeCommand = 'unauthorize2'
        self.AddSudoCommand = 'addsudo2'
        self.RmSudoCommand = 'rmsudo2'
        self.PingCommand = 'ping2'
        self.RestartCommand = 'restart2'
        self.StatsCommand = 'stats2'
        self.HelpCommand = 'help2'
        self.LogCommand = 'log2'
        self.SpeedCommand = 'speedtest2'
        self.CloneCommand = 'clone2'
        self.CountCommand = 'count2'
        self.WatchCommand = 'watch2'
        self.TarWatchCommand = 'tarwatch2'
        self.DeleteCommand = 'del2'
        self.ShellCommand = 'shell2'
        self.ExecHelpCommand = 'exechelp2'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
